Repository ParansaikStudy/FinTrack, pull requests merged in 2025-04, with the labels that each got.

#2 코드 정리 튜토리얼
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/com/track/fin/service/AccountService.java
  src/main/java/com/track/fin/service/TransactionService.java
Labels: 개발

#6 refactor: Service 패키지 제외 모든 패키지 컨벤션 수정
  .gitignore
  src/main/java/com/track/fin/FinTrackApplication.java
  src/main/java/com/track/fin/controller/AccountController.java
  src/main/java/com/track/fin/controller/TransactionController.java
  src/main/java/com/track/fin/domain/Account.java
  src/main/java/com/track/fin/domain/AccountUser.java
  src/main/java/com/track/fin/domain/Transaction.java
  src/main/java/com/track/fin/dto/AccountDto.java
  src/main/java/com/track/fin/dto/AccountInfo.java
  src/main/java/com/track/fin/dto/CancelBalance.java
  src/main/java/com/track/fin/dto/CreateAccount.java
  src/main/java/com/track/fin/dto/DeleteAccount.java
  src/main/java/com/track/fin/dto/QueryTransactionResponse.java
  src/main/java/com/track/fin/dto/TransactionDto.java
  src/main/java/com/track/fin/dto/UseBalance.java
  src/main/java/com/track/fin/exception/AccountException.java
  src/main/java/com/track/fin/repository/AccountRepository.java
  src/main/java/com/track/fin/repository/AccountUserRepository.java
  src/main/java/com/track/fin/repository/TransactionRepository.java
  src/main/java/com/track/fin/service/AccountService.java
  src/main/java/com/track/fin/service/TransactionService.java
  src/main/java/com/track/fin/type/AccountStatus.java
  src/main/java/com/track/fin/type/ErrorCode.java
  src/main/java/com/track/fin/type/TransactionResultType.java
  src/main/java/com/track/fin/type/TransactionType.java
Labels: 리팩토링

#22 PR 탬플릿 추가
  pull_request_template.md
Labels: 문서

#14 계좌 RUD 구현
  src/main/java/com/track/fin/controller/AccountController.java
  src/main/java/com/track/fin/dto/AccountDto.java
  src/main/java/com/track/fin/dto/AccountInfo.java
  src/main/java/com/track/fin/service/AccountService.java
Labels: 개발
